name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt5 pillow pywin32
      - name: Build executable
        run: |
          pyinstaller main.py --onefile --windowed --icon assets/color.ico --add-data "assets;assets"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeradorEtiquetas
          path: dist/GeradorEtiquetas.exe
